### ISSUE TITLE
Android N crash

### ISSUE THREAD

**Issue by auras** [PhilipsHue/PhilipsHueSDK-Java-MultiPlatform-Android#31]
java.lang.Throwable: Explicit termination method 'close' not called
                                                                        at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                        at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:103)
                                                                        at java.net.Socket.createImpl(Socket.java:451)
                                                                        at java.net.Socket.getImpl(Socket.java:517)
                                                                        at java.net.Socket.setSoTimeout(Socket.java:1108)
                                                                        at com.android.okhttp.Connection.connectSocket(Connection.java:195)
                                                                        at com.android.okhttp.Connection.connect(Connection.java:172)
                                                                        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
                                                                        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
                                                                        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
                                                                        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
                                                                        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
                                                                        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
                                                                        at com.philips.lighting.hue.sdk.connection.impl.PHHueHttpConnection.getData(PHHueHttpConnection.java:74)
                                                                        at com.philips.lighting.hue.sdk.upnp.IPAddressScanner.call(IPAddressScanner.java:36)
                                                                        at com.philips.lighting.hue.sdk.upnp.IPAddressScanner.call(IPAddressScanner.java:12)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                        at java.lang.Thread.run(Thread.java:761)

**Comment by auras** [comment]
It only happens if you enable StrictMode:
```
            StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                    .detectLeakedClosableObjects()
                    .penaltyLog()
                    .penaltyDeath()
                    .build());
```

But still, this should be fixed

**Comment by laszlourszuly** [comment]
How do I "bump" this without... well... bumping it?
